name: tests

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: macos-26
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6
      - name: Set proper xcode version
        run: ./Scripts/xcodeselect.sh
      - name: Run Tests
        run: ./Scripts/test.sh -url ${{ secrets.TESTS_URL }} -appname ${{ secrets.TESTS_APP_NAME }} -urltopin ${{ secrets.TESTS_URL_TO_PIN }} -login ${{ secrets.TESTS_LOGIN }} -password ${{ secrets.TESTS_PASSWORD }}
